POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blog 1",
  "author": "Alice",
  "url": "https://a.com",
  "likes": 2
}

###
GET http://localhost:3001/api/blogs
documentType: application/json