POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "alfred",
  "name": "Alfred Balazire",
  "password": "123456"
}

###
GET http://localhost:3001/api/blogs
documentType: application/json